---
name: Update version

on:
  workflow_call:
    inputs:
      git_repo:
        description: "The repository that contains the manifests (e.g. stuartapp/dx2-demo)"
        required: true
        type: string
      git_branch:
        description: "The branch to get the manifests from (e.g. main)"
        required: false
        type: string
        default: main
      service_name:
        description: "Service name that is being updated"
        required: true
        type: string
      environment:
        description: "Environment that this version update will be deployed to"
        required: true
        type: string
      file:
        description: "Relative path of the file to get the version update"
        required: true
        type: string
      version_json_path:
        description: "Json path of the version"
        required: false
        type: string
        default: .images[0].newTag
      new_version:
        description: "New version to be set"
        required: true
        type: string
    secrets:
      gh_token:
        required: true

concurrency:
  group: update-version

jobs:
  update_version:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.git_repo }}
          token: ${{ secrets.gh_token }}
          ref: ${{ inputs.git_branch }}
      - name: Update version
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '${{ inputs.version_json_path }} = "${{ inputs.new_version }}"' '${{ inputs.file }}'
      - name: Push new version
        uses: EndBug/add-and-commit@v9
        with:
          message: "[skip actions] Update ${{ inputs.service_name }} to version ${{ inputs.new_version }} in ${{ inputs.environment }} environment"
          default_author: github_actor
          pull: '--rebase --autostash'
