---
name: Validate Manifests

on:
  workflow_call:
    inputs:
      git_repo:
        description: "The repository that contains the manifests (e.g. stuartapp/dx2-demo)"
        required: true
        type: string
      git_pr_branch:
        description: "The branch with manifests changes"
        required: true
        type: string
      git_main_branch:
        description: "The main branch of the repository (default: main)"
        required: true
        type: string
        default: main
      manifests_dir:
        description: "Path of manifests directory in the git repository"
        required: true
        type: string
        default: manifests
      service_config_files:
        description: "The configuration files for the service to be synced (relative to the manifests directory) separated by comma"
        required: true
        type: string

jobs:
  sync-manifests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        name: Checkout k8s-manifests

      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.git_repo }}
          path: service
          token: ${{ secrets.STUARTBOT_PERSONAL_ACCESS_TOKEN }}
          ref: ${{ inputs.git_pr_branch }}
          fetch-depth: 0

      - name: Apply changes
        working-directory: service
        run: git merge origin/${{ inputs.git_main_branch }}

      - name: Sync manifests
        id: sync-manifests
        env:
          DATA_VALUES_FILES: ${{ inputs.service_config_files }}
        run: |
          cp -r service/${{ inputs.manifests_dir }} .manifests
          make manifests-sync
          sudo rm -rf .manifests

      - name: Cache all manifests
        uses: actions/cache@v3
        env:
          cache-name: manifests
        with:
          path: .changed_manifests
          key: manifests-${{ github.run_id }}-${{ github.run_number }}

  check-policies:
    needs: sync-manifests
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve manifests
        id: retrieve-manifests
        uses: actions/cache@v3
        with:
          path: .changed_manifests
          key: manifests-${{ github.run_id }}-${{ github.run_number }}
      - name: Validate kyverno policies
        if: steps.retrieve-manifests.outputs.cache-hit == 'true'
        run: make kyverno

  run-tests:
    needs: sync-manifests
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve manifests
        id: retrieve-manifests
        uses: actions/cache@v3
        with:
          path: .changed_manifests
          key: manifests-${{ github.run_id }}-${{ github.run_number }}
      - name: Run validator
        if: steps.retrieve-manifests.outputs.cache-hit == 'true'
        run: make validate

  validate-schemas-beta:
    runs-on:
      - self-hosted
      - stuart-beta
    steps:
      - name: Retrieve manifests
        id: retrieve-manifests
        uses: actions/cache@v3
        with:
          path: .changed_manifests
          key: ${{ inputs.cache_key }}
      - name: install kubeclt
        uses: azure/setup-kubectl@v2.0
      - name: Kubectl dry-run
        run: |
          if [ -d .changed_manifests/beta ]; then
            echo "Manifests for beta were found, running validation"
            ls -R .changed_manifests/
            kubectl apply --validate=true --dry-run=server -R -f .changed_manifests/beta/
          else
            echo "Manifests for beta not found, skipping validation"
          fi

  validate-schemas-dev:
    runs-on:
      - self-hosted
      - stuart-dev
    steps:
      - name: Retrieve manifests
        id: retrieve-manifests
        uses: actions/cache@v3
        with:
          path: .changed_manifests
          key: ${{ inputs.cache_key }}
      - name: install kubeclt
        uses: azure/setup-kubectl@v2.0
      - name: Kubectl dry-run
        run: |
          if [ -d .changed_manifests/dev ]; then
            echo "Manifests for dev were found, running validation"
            ls -R .changed_manifests/
            kubectl apply --validate=true --dry-run=server -R -f .changed_manifests/dev/
          else
            echo "Manifests for dev not found, skipping validation"
          fi

  validate-schemas-dispload:
    runs-on:
      - self-hosted
      - stuart-dispload
    steps:
      - name: Retrieve manifests
        id: retrieve-manifests
        uses: actions/cache@v3
        with:
          path: .changed_manifests
          key: ${{ inputs.cache_key }}
      - name: install kubeclt
        uses: azure/setup-kubectl@v2.0
      - name: Kubectl dry-run
        run: |
          if [ -d .changed_manifests/dispload ]; then
            echo "Manifests for dispload were found, running validation"
            ls -R .changed_manifests/
            kubectl apply --validate=true --dry-run=server -R -f .changed_manifests/dispload/
          else
            echo "Manifests for dispload not found, skipping validation"
          fi

  validate-schemas-mgmt:
    runs-on:
      - self-hosted
      - stuart-mgmt
    steps:
      - name: Retrieve manifests
        id: retrieve-manifests
        uses: actions/cache@v3
        with:
          path: .changed_manifests
          key: ${{ inputs.cache_key }}
      - name: install kubeclt
        uses: azure/setup-kubectl@v2.0
      - name: Kubectl dry-run
        run: |
          if [ -d .changed_manifests/mgmt ]; then
            echo "Manifests for mgmt were found, running validation"
            ls -R .changed_manifests/
            kubectl apply --validate=true --dry-run=server -R -f .changed_manifests/mgmt/
          else
            echo "Manifests for mgmt not found, skipping validation"
          fi

  validate-schemas-prod:
    runs-on:
      - self-hosted
      - stuart-prod
    steps:
      - name: Retrieve manifests
        id: retrieve-manifests
        uses: actions/cache@v3
        with:
          path: .changed_manifests
          key: ${{ inputs.cache_key }}
      - name: install kubeclt
        uses: azure/setup-kubectl@v2.0
      - name: Kubectl dry-run
        run: |
          if [ -d .changed_manifests/prod ]; then
            echo "Manifests for prod were found, running validation"
            ls -R .changed_manifests/
            kubectl apply --validate=true --dry-run=server -R -f .changed_manifests/prod/
          else
            echo "Manifests for prod not found, skipping validation"
          fi

  validate-schemas-qa:
    runs-on:
      - self-hosted
      - stuart-qa
    steps:
      - name: Retrieve manifests
        id: retrieve-manifests
        uses: actions/cache@v3
        with:
          path: .changed_manifests
          key: ${{ inputs.cache_key }}
      - name: install kubeclt
        uses: azure/setup-kubectl@v2.0
      - name: Kubectl dry-run
        run: |
          if [ -d .changed_manifests/qa ]; then
            echo "Manifests for qa were found, running validation"
            ls -R .changed_manifests/
            kubectl apply --validate=true --dry-run=server -R -f .changed_manifests/qa/
          else
            echo "Manifests for qa not found, skipping validation"
          fi

  validate-schemas-sandbox:
    runs-on:
      - self-hosted
      - stuart-sandbox
    steps:
      - name: Retrieve manifests
        id: retrieve-manifests
        uses: actions/cache@v3
        with:
          path: .changed_manifests
          key: ${{ inputs.cache_key }}
      - name: install kubeclt
        uses: azure/setup-kubectl@v2.0
      - name: Kubectl dry-run
        run: |
          if [ -d .changed_manifests/sandbox ]; then
            echo "Manifests for sandbox were found, running validation"
            ls -R .changed_manifests/
            kubectl apply --validate=true --dry-run=server -R -f .changed_manifests/sandbox/
          else
            echo "Manifests for sandbox not found, skipping validation"
          fi
